on: [push]

name: AzureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure 
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: checkout source code
      - uses: action/checkout@v2

      - name: Deeploy ARM Template
      - uses: azure/CLI@v1
        with:
         azcliversion: 2.0.72
         inlineScript: |
           az deployment group carete \
           --name StorageAccountDeployment \
           --resource-group githubtestdemo \
           --template-file armtemplates/storageaccount.json \
           -parameters storageAccountType=Standard_LRS
